site_name: Mkdocs template
repo_url: https://github.com/speaknowpotato/mkdocs-template
repo_name: GitHub
site_description:
site_author: Max


# theme:
#   name: material
#   font: false
#   icon:
#     admonition:
#       <type>: material/alert


theme:
  name: material
  # custom_dir: !ENV [THEME_DIR, "material"]
  # custom_dir: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo


dev_addr: 127.0.0.1:8001

extra_css:
  - stylesheets/extra.css

# markdown_extensions:
#   # admonitions, https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=expand
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences

#   - attr_list
#   - def_list
#   - pymdownx.tasklist:
#       custom_checkbox: true

#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - toc:
#       permalink: true


# reference: https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# nav:
#   - Home: index.md  
#   - Python: python/...

plugins:
  - search
  - awesome-pages # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - mkdocs-jupyter
  - tags:  
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago  # date, datetime, iso_date, iso_datetime, timeago
  # - meta  # https://squidfunk.github.io/mkdocs-material/reference/#configuration
